apiVersion: skaffold/v1
kind: Config
metadata:
  name: notifications
deploy:
  kubectl:
    manifests:
      - k8s/notifications.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: discoenv/notifications
  local: {}
